{{- if .Values.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.serverName" . }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "n8n.componentLabels" (dict "context" . "component" "server") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "n8n.componentLabels" (dict "context" . "component" "server") | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.server.extraArgs }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "n8n.envConfigName" . }}
            - secretRef:
                name: {{ include "n8n.envSecretName" . }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.server.readinessProbe.path }}
              port: {{ .Values.server.service.port }}
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.livenessProbe.path }}
              port: {{ .Values.server.service.port }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - name: n8n
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: n8n
          persistentVolumeClaim:
            claimName: {{ include "n8n.pvcName" . }}
{{- end }}
