apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openstatus.configName" . }}
  labels:
    {{- include "openstatus.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "openstatus.databaseUrl" . | quote }}
  DB_URL: {{ include "openstatus.databaseUrl" . | quote }}
  FLY_REGION: {{ .Values.config.flyRegion | quote }}
  GCP_LOCATION: {{ .Values.config.gcpLocation | quote }}
  GCP_PROJECT_ID: {{ .Values.config.gcpProjectId | quote }}
  NEXT_PUBLIC_OPENPANEL_CLIENT_ID: {{ .Values.config.nextPublicOpenpanelClientId | quote }}
  NEXT_PUBLIC_SENTRY_DSN: {{ .Values.config.nextPublicSentryDsn | quote }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: {{ .Values.config.nextPublicStripePublishableKey | quote }}
  NEXT_PUBLIC_URL: {{ include "openstatus.dashboardUrl" . | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  OPENSTATUS_INGEST_URL: {{ include "openstatus.ingestUrl" . | quote }}
  QSTASH_URL: {{ .Values.config.qstashUrl | quote }}
  SCREENSHOT_SERVICE_URL: {{ .Values.config.screenshotServiceUrl | quote }}
  SELF_HOST: {{ .Values.config.selfHost | quote }}
  TINYBIRD_URL: {{ include "openstatus.tinybirdUrl" . | quote }}
  TURBO_ENV_MODE: {{ .Values.config.turboEnvMode | quote }}
  UPSTASH_REDIS_REST_URL: {{ .Values.config.upstashRedisRestUrl | quote }}
  WORKSPACES_HIDE_URL: {{ .Values.config.workspacesHideUrl | quote }}
  WORKSPACES_LOOKBACK_30: {{ .Values.config.workspacesLookback30 | quote }}
