apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstatus.secretName" . }}
  labels:
    {{- include "openstatus.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_GITHUB_ID: {{ .Values.secret.authGithubId | quote }}
  AUTH_GITHUB_SECRET: {{ .Values.secret.authGithubSecret | quote }}
  AUTH_GOOGLE_ID: {{ .Values.secret.authGoogleId | quote }}
  AUTH_GOOGLE_SECRET: {{ .Values.secret.authGoogleSecret | quote }}
  AUTH_SECRET: {{ .Values.secret.authSecret | quote }}
  BLOB_READ_WRITE_TOKEN: {{ .Values.secret.blobReadWriteToken | quote }}
  CRON_SECRET: {{ .Values.secret.cronSecret | quote }}
  DATABASE_AUTH_TOKEN: {{ .Values.secret.databaseAuthToken | quote }}
  GCP_CLIENT_EMAIL: {{ .Values.secret.gcpClientEmail | quote }}
  GCP_PRIVATE_KEY: {{ .Values.secret.gcpPrivateKey | quote }}
  OPENPANEL_CLIENT_SECRET: {{ .Values.secret.openpanelClientSecret | quote }}
  PAGERDUTY_APP_ID: {{ .Values.secret.pagerdutyAppId | quote }}
  PLAYGROUND_UNKEY_API_KEY: {{ .Values.secret.playgroundUnkeyApiKey | quote }}
  PROJECT_ID_VERCEL: {{ .Values.secret.projectIdVercel | quote }}
  QSTASH_CURRENT_SIGNING_KEY: {{ .Values.secret.qstashCurrentSigningKey | quote }}
  QSTASH_NEXT_SIGNING_KEY: {{ .Values.secret.qstashNextSigningKey | quote }}
  QSTASH_TOKEN: {{ .Values.secret.qstashToken | quote }}
  RESEND_API_KEY: {{ .Values.secret.resendApiKey | quote }}
  SENTRY_AUTH_TOKEN: {{ .Values.secret.sentryAuthToken | quote }}
  SLACK_SUPPORT_WEBHOOK_URL: {{ .Values.secret.slackSupportWebhookUrl | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secret.stripeSecretKey | quote }}
  STRIPE_WEBHOOK_SECRET_KEY: {{ .Values.secret.stripeWebhookSecretKey | quote }}
  SUPER_ADMIN_TOKEN: {{ .Values.secret.superAdminToken | quote }}
  TEAM_ID_VERCEL: {{ .Values.secret.teamIdVercel | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secret.telegramBotToken | quote }}
  TINY_BIRD_API_KEY: {{ .Values.secret.tinyBirdApiKey | quote }}
  UNKEY_API_ID: {{ .Values.secret.unkeyApiId | quote }}
  UNKEY_TOKEN: {{ .Values.secret.unkeyToken | quote }}
  UPSTASH_REDIS_REST_TOKEN: {{ .Values.secret.upstashRedisRestToken | quote }}
  VERCEL_AUTH_BEARER_TOKEN: {{ .Values.secret.vercelAuthBearerToken | quote }}
